### ISSUE TITLE
Replace defaultOptions with addOptions

### ISSUE THREAD

**Issue by samuelhauser** [unicscode/tiptap-clean-paste#4]
In the newest version of Tiptap, the defaultOptions is replaced with addOptions.

I really like this Plugin. Thanks for keeping this up-to-date

**Comment by unicscode** [comment]
Thank you for your positive feedback on the plugin! I'm glad you find it useful. 

You're absolutely right about the change in Tiptap's API.
I'll update the plugin to  to ensure compatibility with the newest version of Tiptap.

If you have any other suggestions or notice any other areas that need updating, please don't hesitate to let me know.
